### PR TITLE
Added preferred countries support

### PR DESCRIPTION
**Pull request by mikob**
preferred countries are at the top of the list

### CODE REVIEW

**Comment by iamstevendao** [comment]
Thanks a lot for your contribution!! 
Can you pull the new commits then push your code upon them? There are some places it might be not up-to-date with the current version.

**Comment by mikob** [comment]
@iamstevendao I already rebased this branch before making the PR. You can see my commit on top of yours in this commit view: https://github.com/mikob/vue-tel-input/commits/preferred-countries

**Comment by iamstevendao** [comment]
hmm, I added `disabledFetchingCountry` prop in the `src/vue-tel-input.vue` but you removed it in your commit, can I know why?
Also, can you ignore `dist` and `docs` folders? 
I committed them just for the demo and publish purpose, of course, I will rebuild after merge your changes

**Comment by mikob** [comment]
@iamstevendao thanks for fixing my merge mistake, and thanks for merging all the changes!

**Comment by iamstevendao** [comment]
@mikob You are always welcome, thanks for your help :tada:

**Pull request merged**
