### PR TITLE
fix: change country flag on click, even if international mode is NOT used

### PR DESCRIPTION
**Pull request by suits-at**
This PR also extracts the css so you can import it, if you are using the component directly (and not as a plugin).
Also we added the ability to change the input property "type" via a property, if needed.

### CODE REVIEW

**Comment by iamstevendao** [comment]
@suits-at Thanks for your help! I have some doubts:
- What are other use cases of `type` apart from `'tel'`?
- `default: () => getDefault('tel')` is wrong, should be `default: () => getDefault('type')`.
- `css: { extract: true }` is default in prod, as stated in the vue documentation https://cli.vuejs.org/config/#css-extract

**Comment by suits-at** [comment]
> @suits-at Thanks for your help! I have some doubts:
> 
> * What are other use cases of `type` apart from `'tel'`?
> * `default: () => getDefault('tel')` is wrong, should be `default: () => getDefault('type')`.
> * `css: { extract: true }` is default in prod, as stated in the vue documentation https://cli.vuejs.org/config/#css-extract

Thanks for your fast reply @iamstevendao. 

1. We use your library for a login, where the user can enter either an email or a phone number. On mobile devices `type="tel"` restricts keyboard inputs to numbers only. Therefore we need to set `type="text"` - otherwise users can't input emails.
2. True - my mistake. I corrected this one.
3. Also correct - I reverted this one.

**Comment by simllll** [comment]
Regarding extract css, to be more compatible to the old appraoch, is setting it to false an option?
"When building as a library, you can also set this to false to avoid your users having to import the CSS themselves." 
then all styles are inlined, and behaviour does not change (e.g. someone does not have to inlcude css explicity)

**Comment by iamstevendao** [comment]
@suits-at awesome, thank you! :tada:

**Comment by iamstevendao** [comment]
@simllll I believe we had some people complaining about this and we got to extract css to a separate file (it used to be injected in js file before).

**Comment by simllll** [comment]
> @simllll I believe we had some people complaining about this and we got to extract css to a separate file (it used to be injected in js file before).

Okay, in general also fine for me.. I think it's just more convenient, and some SSR optimizations are only working when styles are inlined. But we can move this discussion to the future ;-)  (and to a seperat thread ;-))

**Pull request merged**
