### PR TITLE
Update types for classes

### PR DESCRIPTION
**Pull request by shavidzet**
Array and object types work also for classes

### CODE REVIEW

**Comment by iamstevendao** [comment]
@shavidzet Should we update the type of props in the component as well?

**Comment by shavidzet** [comment]
> @shavidzet Should we update the type of props in the component as well?

Yeah, I've updated component's source props too, please take a look my latest commit

**Comment by iamstevendao** [comment]
I got this error when trying to pass an `array`
Screen Shot 2019-06-22 at 19 32 40

**Comment by iamstevendao** [comment]
Anyway, I changed to `[String, Array, Object]` instead of `String || Array || Object`. It should be in [v2.2.6](https://github.com/EducationLink/vue-tel-input/releases/tag/v2.2.6)

**Pull request closed without merging**
