### PR TITLE
Add created-hook

### PR DESCRIPTION
**Pull request by kalcifield**
Added a created-hook so the component can be loaded with a phone number.

### CODE REVIEW

**Comment by kalcifield** [comment]
#8

**Comment by prajwalbharadwaj** [comment]
On loading of the page, the input wont update with the preloaded number

**Comment by prajwalbharadwaj** [comment]
image

**Comment by iamstevendao** [comment]
@prajwalbharadwaj What are the steps to reproduce the issue? can you make it happen in the demo page? https://codesandbox.io/s/bold-butterfly-0yyyk45q7w?from-embed

**Comment by prajwalbharadwaj** [comment]
Hey Steven
I am sorry. Yeah it worked fine.

**Pull request merged**
