### PR TITLE
Add RegExp to validate num

### PR DESCRIPTION
**Pull request by Lmpgdn**
Fixed `isValid` still returns `true ` when adding text after a valid number.
[preview](https://prnt.sc/k2pv2d)

### CODE REVIEW

**Comment by ajmas** [comment]
Just curious whether these changes would better being part of the 'libphonenumber-js' package? Unfortunately, due to conflicts I am not sure what the changes were.

**Comment by iamstevendao** [comment]
Now we have `validCharactersOnly` prop to prevent users from typing letters to the input, available from [v2.4.0](https://github.com/EducationLink/vue-tel-input/releases/tag/v2.4.0)

**Comment by Lmpgdn** [comment]
> Just curious whether these changes would better being part of the 'libphonenumber-js' package? Unfortunately, due to conflicts I am not sure what the changes were. Also, probably best reference an issue number?

Sorry, I have been inactive for a while. It was my first time submitting a pull request and probably followed the wrong instructions when committing, which resulted in conflicts with this commit 😂. 

Glad to see we now have this feature, though. Thanks!

**Comment by iamstevendao** [comment]
@Lmpgdn That's alright. Thanks for your help, I appreciate it!

**Pull request closed without merging**
